### ISSUE TITLE
Add Demographic Checkboxes On Request Form

### ISSUE THREAD

**Issue by mekkim** [EBSECan/donatemask#126]
I met again with Canadian Red Cross and they have asked us to gather more demographic data of requestors so that they can justify that we qualify under the strict parameters of their program agreement with Health Canada.  I suggest the following:

On the request form, below the `Choose Requestor Type` pull list, add "This request is by or for one or more of the following:" followed by checkboxes for various vulnerable groups that we are targeting (any amount including zero can be checked).  These would simply add a binary value to the request for each group in the database push, where "no check" is "false" and "check" is true" for each category (I'm open to a better approach here)

Suggested categories to list (open to expansion!):

- Seniors
- Disabled folk
- Members of LGBTQ2S+
- People experiencing or at risk for homelessness
- People with low or no income
- Children/youth
- Indigenous Peoples
- Other vulnerable population not listed here

**Comment by humphd** [comment]
I've done more research, and I think I have a better sense of what's needed.  I'll work on this with @emmaelaine.

**Comment by humphd** [comment]
A quick update on this to let you know that we're close to having a PR ready to submit.  It's coming soon!

**Comment by mekkim** [comment]
I created a couple of test requests with demographics. I don't see the new collection in the database.  Is it possible something didn't sync on the back end?

**Comment by mekkim** [comment]
Totally my mistake.  I forgot to update some DB components/routes on the live server.  Should be fixed now.
