### ISSUE TITLE
Add CO2.click Models C & D to our Charity Store

### ISSUE THREAD

**Issue by mekkim** [EBSECan/donatemask#130]
Our friends at CO2.click have offered to have us distribute their Model C CO2 detector and desk mount as a kit on our charity store.  It's all Canadian designed and assembled and less expensive than the ARANET 4 (not Canadian) with similar functionality.  Plus, they're open source friendly so there's discussion of a subsequent "Maker" version that's all open source in the future!

We can add it to our charity store (donatemask.ca/store) right away and begin getting orders.  Details are here, including link to data sheet and quick start guide: [https://www.co2.click/ecommerce/en/Model-C.html](https://www.co2.click/ecommerce/en/Model-C.html)
Our price will be $269.99 (including taxes and shipping in Canada) for the Model C + desktop adapter option (as a kit).

**Comment by NetForces** [comment]
If you have any questions I'm Andre the guy behind co2.click ;-)

**Comment by humphd** [comment]
Great!  I'll work on this (implementation) and get @emmaelaine to help me figure out the design.

**Comment by mekkim** [comment]
Since pre-orders are now coming in via Twitter, I've set up the Stripe product link: [https://buy.stripe.com/bIY29Wbu9byL2ZyfZ9](https://buy.stripe.com/bIY29Wbu9byL2ZyfZ9)

**Comment by mekkim** [comment]
I've discussed with @NetForces.  We'll also list the Model D, but have it as a wall-mount kit instead of desk-mount kit.  It's also black instead of white.  And has no cloud wifi/cloud connection (which some people like to not have!).  Details: [https://www.co2.click/ecommerce/en/Model-D.html](https://www.co2.click/ecommerce/en/Model-D.html).  We're discussing price presently.

**Comment by mekkim** [comment]
Model D with wall-mount adapter kit: [https://buy.stripe.com/8wMeWI2XD5an43C3cq](https://buy.stripe.com/8wMeWI2XD5an43C3cq)
