### ISSUE TITLE
Visualize the reach of requests across Canada on Summary page

### ISSUE THREAD

**Issue by humphd** [EBSECan/donatemask#141]
As the number of fulfilled mask and test requests increases, we have an interesting dataset.  I did an experiment to see what the distribution looks like, and produced this image:

<img width="1151" alt="Screen Shot 2022-06-23 at 11 13 53 AM" src="https://user-images.githubusercontent.com/427398/175334010-3741c236-88ac-4592-9ef6-ccd7c7942803.png">

It's interesting for what it shows, and what it lacks.  On the one hand, good coverage from coast to coast, awesome to see so much activity in the Maritimes; but also not enough in Quebec (I'm hoping #124 will help), and not enough in the north.  Armed with this knowledge, it might be good to reach out to communities in places that we aren't serving, and see if we can help.

I'm thinking to write some code to automate generating this image once per day and add it to the Summary page, and wondered if others thought that was a good idea?

NOTE: we wouldn't put this up as an interactive map (e.g. you couldn't zoom, or extract any info about where people are located).  I'm using Postal Code proxy co-ordinates to generate this.

**Comment by humphd** [comment]
I don't want to make it interactive because I don't want to expose, or even hint at, actual data points.  I'm just trying to give a 10,000 foot view of the community affected by the work.

We're hoping to throw away a lot of the data we store for PII anonymity (#128).

**Comment by Sync271** [comment]
Yup, I get that we don't want to expose or even hint at actual data points and that is why I thought heatmaps would serve better since we can aggregate based on unique zip codes while not exposing anything more than the zipcode/area.

**Comment by mekkim** [comment]
I LOVE THIS SO MUCH!  My only suggestion is that we make it Canada-only.  Even if it ends up not being geographically uniform (i.e., we skew province sizes for fit rather than actual size), a centralized Canada-focus for the map fits our Canada-focus of the charity!
With the demographics collection properly updated it will be possible to filter by demographics as well, as a future enhancement.
WOOOO!

**Comment by humphd** [comment]
I'm not 100% sure how to accomplish the "Canada-only" bit.  I'm aware of 2 options, neither of which is perfect:

1. Define a polygon around the Canadian border, and dim out the rest of the map (e.g. kind of like [this map of France](http://jsfiddle.net/FranceImage/1yaqtx9u/)).  I could get the edges to be cleaner but it will still look like this.
2. Not use map tiles at all, and draw the map as a set of SVG shapes, like [this map of Canada](http://www.codewritingcow.com/d3-js/maps/americas/canada/).  The issue here is that you lose all the context (i.e., city names).  Maybe that's OK?

The other thing about only showing Canada, is that just about all the points are going to be directly on the bottom of the map.  Right now, they are kind of centred.  When it's only Canada, it will always look like the country is empty (i.e., because it is!).

**Comment by mekkim** [comment]
You make good points! I'm all for whatever is easiest.  Getting something up is a great start.  We can refine later if/when we want to optimize the look.

**Comment by humphd** [comment]
OK, here's how I'm going to approach this.  The code to make this work requires a 35M file of postal code geolocation data, which is too big to run in the browser.  To deal with this, I'm going to generate this image "server side" and we'll load the final product in the front-end.  Because I want to update this regularly (every 8 hours or so), I'll do it as a GitHub Action in a new repo that I'll create in a minute.  The code will run on its own in GitHub Actions, without interfering with anything, produce the final image, commit it back to the new repo, and let the front-end web app use it like any other remote image.

I'll put links here to the repo when I've got if finished.

**Comment by mekkim** [comment]
Super duper amazing!

**Comment by mekkim** [comment]
Super duper wooper! Amazeballs!

**Comment by humphd** [comment]
Confirmed this is working: see automated commits at https://github.com/EBSECan/canada-map-requests/commits/main.  That means I can move forward with using it in web app next.
