### ISSUE TITLE
Add Priority Pull List to Request Form

### ISSUE THREAD

**Issue by mekkim** [EBSECan/donatemask#156]
As Sarah and I are getting overwhelmed by more quests for masks and tests coming in than we can keep up with fulfilling, we've discussed a few options and figured that borrowing from open source bug triage might be a good approach.  We suggest the addition of a priority pull list on the request form where folk scan self-select a priority.  We'll have a legend that explains what each priority level means (per below) and a disclaimer that we don't promise to follow the priority but may use it if it makes sense for our triaging.  We DO want to prioritize disabled folk who are forced to attend unsafe, in-person medical visits, for example.  We're not concerned about misuse because we can always opt to ignore and the current situation is no information, so at worst we ignore and default to what we have now which is "unknown" priority (unless someone mentions in the comments, but it's harder to search on that when fulfilling requests).

Suggested priority levels in pull list:

1. High (Legend: Upcoming, unavoidable high-risk event/appointment for which no protection is currently available. Needed ASAP.)
2. Normal (Default.  Legend: It would be nice to have masks/tests, but I won't be in danger if they're delayed a couple of weeks.)
3. Low (Legend: Fill order when possible, but no hurry. Will not impact my safety.)

**Comment by humphd** [comment]
Sounds like a good idea.  Watching the success of the outreach campaigns, it's clear that setting expectations for what's possible is important.  I'll work on something.

Question: do you also want to include some kind of language above the form that helps people understand what's likely when they make a request (i.e., emphasize this is a volunteer effort, etc)?  If you have thoughts, throw them in here.

**Comment by mekkim** [comment]
Sure.  I'm flexible on how we do the info/expectation management.  How about a show-and-tell in a "life of your request" type approach that mirrors the Mozilla bug lifecycle?  Like a behind-the-scenes tutorial of what happens once they hit "submit".  For example:

```
1. When you hit submit, assuming you entered all the necessary information correctly (if not, the form will prompt you for a correction before you can submit!), your request gets time-stamped and then is added to a secure MongoDB NOSQL database that only select volunteers who are in charge of fulfilling orders have access to via unique username and secure password.
2. Fulfillment volunteers go to the database and pull unfulfilled requests that are flagged with "requestFulfilled=false" (the default, when a request is submitted).  They may also optionally filter the requests based on time (trying to do order requests before newer requests!), priority (high > low), availability of products (if we're out of RATs, we may focus on requests JUST for masks until our RAT refill is received from Canadian Red Cross (as was the case in May/June 2022)), location (we sometimes prioritize rapid tests for the Eastern provinces in Canada whose governments have not made them as easy to access as for folks in Ontario, Quebec, and BC), and so on.\
3. Volunteers take the returned requests and pack envelopes, shipping bags, and/or boxes depending on the size of the order and either put stamps on the envelope, if it's small enough for Canada Post Lettermail (< 50g and envelope-ish dimensions), or create a shipping label via Canada Post Snap Ship's online tool for businesses (using our parent charity EBSECan's corporate account).  Most often, packages are shipped via Canada Post Expedited Parcel as it is the best time/cost tradeoff in most cases.  For select orders, we may use Canada Post Xpresspost from time to time.  Regular Parcel service is almost never used as it's almost always nearly the same price as Expedited Parcel for us (we get a "small business" discount from Canada Post that makes Expedited Parcel more affordable), so we go with the faster service to get your masks and tests to you sooner!  When Expedited Parcel or Xpresspost are used, we enter the email address of the requestor into Canada Post's tracking system when we create the shipping label.  In this manner, requestors get an email from Canada Post with a tracking number so they can see the status of their package.
4. Once stamps/labels are affixed, the volunteers build a giant pile of them (see pictures on our Twitter) and pack their cars with all the packages and drive them to the local Canada Post outlet, whose employees now know us well!.  Lettermail envelopes are put in regular mailboxes and packages are handed ready to go to the Canada Post outlet employees.  From there, Canada Post does its thing, routing envelopes and packages across the country!
5. And so on...
```

We could also add description of how the stats are calculated and gathered and assembled on the summary page for people's interest and include it above.  And or other things!  Something about volume (more orders than volunteer packing ability) should probably be mentioned in the "goes to database and queries" section or thereabouts.  
I turn to our writing-expert volunteers to help make this better!
