### ISSUE TITLE
Add News Section to Website

### ISSUE THREAD

**Issue by mekkim** [EBSECan/donatemask#163]
Now that we are getting national press coverage, it would be nice to have a news/announcements/etc. page on the site to keep track of them.  Maybe it would be better if it were linked at the bottom of the page so as to not overcram the header?  I leave the UI choices to the experts!

**Comment by mekkim** [comment]
Some initial links to add to the news section when it's up:

[Mekki in National Post discussing motivations of founding the charity](https://nationalpost.com/sponsored/health-sponsored/immune-compromised-individuals-are-embracing-layers-of-covid-related-support-protection-and-treatment)

[Mekki quoted calling out Canadian Blood Services and offering masks from Donate Mask if they reinstate masking policy in Ottawa Citizen](https://ottawacitizen.com/news/local-news/our-kids-need-that-blood-to-live-donors-recipients-upset-after-canadian-blood-services-lifts-mask-mandates)

[Mekki quoted in The Saltwire / The Telegram (Newfoundland) talking about distributing rapid tests across NFL and Canada](https://www.saltwire.com/newfoundland-labrador/news/local/the-great-rat-debate-newfoundland-and-labrador-still-holds-reins-on-rapid-tests-100716862/)

**Comment by PreciousOlamide** [comment]
hello, I will like to work on this task if assigned to me.

**Comment by yaswanthtondepu** [comment]
HI @mekkim 
Which design is good?
A)
![image](https://user-images.githubusercontent.com/26676435/185004184-f8ed7e78-8e4e-4104-8789-6f0076d0c9ed.png)

B)
![image](https://user-images.githubusercontent.com/26676435/185004412-480e02cc-1011-44de-8751-7b61bf8bdcf6.png)

If you have any other ideas, please share them with me. Also, what should be the text under "News" title

**Comment by mekkim** [comment]
> hello, I will like to work on this task if assigned to me.

Folks can self select to tasks.  No need to wait for assignment or ask for approval.  Do whatever you find interesting!

**Comment by mekkim** [comment]
> HI @mekkim Which design is good? A) ![image](https://user-images.githubusercontent.com/26676435/185004184-f8ed7e78-8e4e-4104-8789-6f0076d0c9ed.png)
> 
> B) ![image](https://user-images.githubusercontent.com/26676435/185004412-480e02cc-1011-44de-8751-7b61bf8bdcf6.png)
> 
> If you have any other ideas, please share them with me. Also, what should be the text under "News" title

Both look good to me.  I suck at UI stuff so I will defer to others with a better eye for making things look good.  @PaytonthePerson maybe?  
I'm neutral on what the news header says.  Maybe take a look at some examples for other charities' news sites?

**Comment by PaytonthePerson** [comment]
> HI @mekkim 
> 
> Which design is good?
> 
> A)
> 
> ![image](https://user-images.githubusercontent.com/26676435/185004184-f8ed7e78-8e4e-4104-8789-6f0076d0c9ed.png)
> 
> 
> 
> B)
> 
> ![image](https://user-images.githubusercontent.com/26676435/185004412-480e02cc-1011-44de-8751-7b61bf8bdcf6.png)
> 
> 
> 
> If you have any other ideas, please share them with me. Also, what should be the text under "News" title
> 
> 
> 
> 
> 
> 

Personally, I like the second one, bc it feels less cramped it think? It would prob look cooler if there were pics of there articles like yk in news sites? Idk what site ur on so idk if that's possible lol 
Looks rly good tho! :D

**Comment by mekkim** [comment]
Great work, @yaswanthtondepu.  Thanks for the visual review @PaytonthePerson!
