### ISSUE TITLE
Add Large Mask Option to Request Field

### ISSUE THREAD

**Issue by mekkim** [EBSECan/donatemask#166]
We've been receiving an increasing number of special requests for large-size masks. I've been able to source a supply with Canadian manufacturers (same as the small ones - Eclipse Horizon Large) at reasonable prices, so I think it's time we give that option to requestors as well.

It's just the addition of a field: "Number of Large masks" to go with number of small, number of regular, and number of tests.

**Comment by PreciousOlamide** [comment]
hello, I will like to work on this task if assigned to me.

**Comment by humphd** [comment]
@PreciousOlamide did you want to fix #167 first?  This one is more complicated.

**Comment by PreciousOlamide** [comment]
Hello,
I am so glad you assigned me the task
I will work on #166 first

**Comment by PreciousOlamide** [comment]
Hello, I changed my mind and decide to work on #167 first since it might
it's harder

**Comment by yaswanthtondepu** [comment]
Hello, 
I would like to work on this.

**Comment by yaswanthtondepu** [comment]
Hello, is anyone working on this issue

**Comment by PreciousOlamide** [comment]
> 

Hello
I am working on it but I need the moderators to answer some of my enquiries before I can continue 
Did you notice the size chart on twitter is a bit odd????

**Comment by yaswanthtondepu** [comment]
Hello @mekkim,
I have done changes and added large masks. I made changes in the front end, back end, and test files. I am sure about the front end part but not about the back end. I can give a pull request if you want to check the code.

![image](https://user-images.githubusercontent.com/26676435/184949497-5e00c171-2d6f-4bc8-abe9-24a08b84985f.png)

**Comment by mekkim** [comment]
Hi @yaswanthtondepu,
Looks good!  Yes, create a pull request and tag me for review.
Thanks!
M.

**Comment by mekkim** [comment]
Great work @yaswanthtondepu!
