### ISSUE TITLE
Scroll Restoration When Switching Pages

### ISSUE THREAD

**Issue by mekkim** [EBSECan/donatemask#46]
I'd like to validate that we have the scroll restoration working correctly as I think it might be responsible for why the Google Ads screw up sometimes above/below the menu bar: https://v5.reactrouter.com/web/guides/scroll-restoration

If we're following the principles in that guide correctly then it's something else breaking the ads.

**Comment by mekkim** [comment]
Closing as this is probably a non-issue.

**Comment by humphd** [comment]
It's a big issue with React SPAs in general.  There aren't any great solutions (that I'm aware of), only hacks.  You have to manually store the the position and use hooks to try and scroll to it with JS.  Every time I've done it, it feels close but also wrong (i.e., not what the browser would do).

**Comment by humphd** [comment]
#131 is related to this.
