### ISSUE TITLE
Direct Links to Any of The Routes Crash

### ISSUE THREAD

**Issue by Sync271** [EBSECan/donatemask#61]
When users use the direct links to [donate](https://donatemask.ca/donate/), [request](https://donatemask.ca/request) or any other route, we get `Cannot GET /request` depending on the route.

**Comment by mekkim** [comment]
Solution is to append the following code in app.js.  Should now be in main and build with new builds of /server

```
app.get('*',(req, res) => {
        // res.redirect('/');
        res.sendFile('/home/donatemask/donatemask.ca/public/index.html');
    });
```
Thanks @HaiderZaidiDev!

**Comment by mekkim** [comment]
This issue has reappeared.  Something has changed the above workaround.  For example, `requesttest.ca` no longer resolves correctly.
